### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by xdr-kzh** [Max13/homebrew-odb#7]
Hi. I try to install by using command: `brew install libodb odb libodb-sqlite --with-libstdc++`, but during the installing, I have the next:

```
==> Downloading http://www.codesynthesis.com/download/odb/2.4/odb-2.4.0.tar.gz
Already downloaded: /Users/alejandro/Library/Caches/Homebrew/odb-2.4.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/odb/2.4.0 --libexecdir=/usr/local/Cellar/odb/2.4.0/lib --with-options-file=/usr/local/Cellar/odb/2.4.0/etc/odb/default.options CXXFLAGS=-fno-devirtualize
==> make install
Last 15 lines from /Users/alejandro/Library/Logs/Homebrew/odb/02.make:
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:897:23: error: 'gcc_checking_assert' was not declared in this scope
   gcc_checking_assert (precision == x.get_precision ());
   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h: In instantiation of 'static wi::storage_ref wi::int_traits<generic_wide_int<T> >::decompose(long long int*, unsigned int, const generic_wide_int<storage>&) [with storage = wide_int_ref_storage<true>]':
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:945:48:   required from 'wide_int_ref_storage<SE>::wide_int_ref_storage(const T&, unsigned int) [with T = generic_wide_int<wide_int_ref_storage<true> >; bool SE = true]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:722:26:   required from 'generic_wide_int<T>::generic_wide_int(const T&, unsigned int) [with T = generic_wide_int<wide_int_ref_storage<true> >; storage = wide_int_ref_storage<true>]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:1781:41:   required from 'bool wi::ltu_p(const T1&, const T2&) [with T1 = generic_wide_int<wide_int_ref_storage<true> >; T2 = unsigned int]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:1878:17:   required from 'bool wi::geu_p(const T1&, const T2&) [with T1 = generic_wide_int<wide_int_ref_storage<true> >; T2 = unsigned int]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:2850:13:   required from 'typename wi::unary_traits<T>::result_type wi::lshift(const T1&, const T2&) [with T1 = generic_wide_int<wi::extended_tree<128> >; T2 = int; typename wi::unary_traits<T>::result_type = generic_wide_int<fixed_wide_int_storage<128> >]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/tree.h:5366:83:   required from here
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:897:23: error: 'gcc_checking_assert' was not declared in this scope
make[1]: *** [common.lo] Error 1
make[1]: *** [common-query.lo] Error 1
make[1]: *** [context.lo] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/max13/homebrew-odb/issues

These open issues may also help:
Installing odb after a libodb-* package prevent odb to work correctly https://github.com/Max13/homebrew-odb/issues/2
Installing odb + a libodb-* package installs libodb twice https://github.com/Max13/homebrew-odb/issues/1

```

OS X version: 10.11.4 El Capitan

**Comment by Max13** [comment]
@alejandro-pnz Hi and thanks for your report. I've just fixed that, you can retap the packages:

`brew untap max13/odb && brew tap max13/odb`

I suggest you `reinstall` all the installed packages (`brew reinstall libodb odb`)

**Comment by xdr-kzh** [comment]
The same error still appears. I've tried to install the packages by one, and the error is appearing when I try to install **odb** (doesn't matter is installed **libodb** already or not). Also doesn't matter a selection of the compiler (**--with-libstdc++** or **--with-libc++**, or without any selection).

Output:

```
Mac-mini-Alexander:ifunny-android alejandro$ brew install libodb odb libodb-sqlite --with-libstdc++
==> Installing libodb from max13/odb
==> Downloading http://www.codesynthesis.com/download/odb/2.4/libodb-2.4.0.tar.gz
Already downloaded: /Users/alejandro/Library/Caches/Homebrew/libodb-2.4.0.tar.gz
==> Downloading http://scm.codesynthesis.com/?p=odb/libodb.git;a=patch;h=b119086e8c5835695cd851da8ad1393218aa29df
Already downloaded: /Users/alejandro/Library/Caches/Homebrew/libodb--patch-860bdab948a72b30397377201be329c9124594026ff088effe85cc87c39de079.git;a=patch;h=b119086e8c5835695cd851da8ad1393218aa29df
==> Downloading http://scm.codesynthesis.com/?p=odb/libodb.git;a=patch;h=ee4d942916d347ac65f53969941b0fb100760611
Already downloaded: /Users/alejandro/Library/Caches/Homebrew/libodb--patch-d58490df7cc415bd55373aaebc185b5e4e60275a4536a737fcd22196393dd831.git;a=patch;h=ee4d942916d347ac65f53969941b0fb100760611
==> Patching
==> Applying libodb.git;a=patch;h=b119086e8c5835695cd851da8ad1393218aa29df
patching file odb/no-id-object-result.hxx
patching file odb/polymorphic-object-result.hxx
patching file odb/result.hxx
patching file odb/result.txx
patching file odb/simple-object-result.hxx
patching file odb/view-result.hxx
==> Applying libodb.git;a=patch;h=ee4d942916d347ac65f53969941b0fb100760611
patching file odb/database.hxx
patching file odb/database.ixx
==> ./configure --prefix=/usr/local/Cellar/libodb/2.4.0 CXX=clang++ -stdlib=libstdc++
==> make install
Warning: Your app, libodb and its libs must be compiled with the same
C++ standard library. Currently: libstdc++
🍺  /usr/local/Cellar/libodb/2.4.0: 143 files, 785.6K, built in 20 seconds
==> Installing odb from max13/odb
==> Downloading http://www.codesynthesis.com/download/odb/2.4/odb-2.4.0.tar.gz
Already downloaded: /Users/alejandro/Library/Caches/Homebrew/odb-2.4.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/odb/2.4.0 --libexecdir=/usr/local/Cellar/odb/2.4.0/lib --with-options-file=/usr/local/Cellar/odb/2.4.0/etc/odb/default.options CXXFLAGS=-fno-devirtualize
==> make install
Last 15 lines from /Users/alejandro/Library/Logs/Homebrew/odb/02.make:
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:897:23: error: 'gcc_checking_assert' was not declared in this scope
   gcc_checking_assert (precision == x.get_precision ());
   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [common.lo] Error 1
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h: In instantiation of 'static wi::storage_ref wi::int_traits<generic_wide_int<T> >::decompose(long long int*, unsigned int, const generic_wide_int<storage>&) [with storage = wide_int_ref_storage<true>]':
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:945:48:   required from 'wide_int_ref_storage<SE>::wide_int_ref_storage(const T&, unsigned int) [with T = generic_wide_int<wide_int_ref_storage<true> >; bool SE = true]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:722:26:   required from 'generic_wide_int<T>::generic_wide_int(const T&, unsigned int) [with T = generic_wide_int<wide_int_ref_storage<true> >; storage = wide_int_ref_storage<true>]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:1781:41:   required from 'bool wi::ltu_p(const T1&, const T2&) [with T1 = generic_wide_int<wide_int_ref_storage<true> >; T2 = unsigned int]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:1878:17:   required from 'bool wi::geu_p(const T1&, const T2&) [with T1 = generic_wide_int<wide_int_ref_storage<true> >; T2 = unsigned int]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:2850:13:   required from 'typename wi::unary_traits<T>::result_type wi::lshift(const T1&, const T2&) [with T1 = generic_wide_int<wi::extended_tree<128> >; T2 = int; typename wi::unary_traits<T>::result_type = generic_wide_int<fixed_wide_int_storage<128> >]'
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/tree.h:5366:83:   required from here
/usr/local/Cellar/gcc/6.1.0_1/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.1.0/plugin/include/wide-int.h:897:23: error: 'gcc_checking_assert' was not declared in this scope
make[1]: *** [common-query.lo] Error 1
make[1]: *** [context.lo] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/max13/homebrew-odb/issues

These open issues may also help:
Installing odb after a libodb-* package prevent odb to work correctly https://github.com/Max13/homebrew-odb/issues/2
Installing odb + a libodb-* package installs libodb twice https://github.com/Max13/homebrew-odb/issues/1
```

**Comment by Max13** [comment]
I've changed the dependencies, it should be installing with gcc6, but with gcc5.

did you do:`brew untap max13/odb`

Then: `brew tap max13/odb` ?

**Comment by xdr-kzh** [comment]
Yes, sure, I made it like in your comment above.
At this moment, it is ok.
Thanks Google, I've found [that](https://forum.manjaro.org/t/makepkg-failing-to-compile-some-packages/1493). The solution was to choose gcc5 version.
I've done next and all packages installed:

```
rm -rf /usr/local/Cellar/gcc/6.1.0_1/
brew install homebrew/versions/gcc5
```

**Comment by Max13** [comment]
Yeah, basically you've pre-installed GCC. Can I ask you to completely remove gcc, odb and all dependencies, then retap my packages, then install odb please?

I need to check if your issue can be reproduced to fix it:

brew uninstall gcc gcc5 libcutl libodb odb
brew untap max13/odb && brew tap max13/odb
brew install libodb odb --with-gcc

Then, if it still doesn't install, I will try to find the issue. Thx

**Comment by xdr-kzh** [comment]
I've done the commands in the order that you described above. After that, all is good (some little not - I don't have gcc package in brew).

**Comment by Max13** [comment]
@alejandro-pnz The error is because you have already installed it. And actually, I think you had your previous error because of `reinstall`. `brew` seems to reinstall the exact same way it installed, thats why `uninstall` then `install` fixed.

Thank you for your help, hope you enjoy it and `odb` as well.
